name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [7.1, 7.2, 7.3, 7.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ matrix.version }}-${{ github.sha }}
          restore-keys: docker-buildx-${{ matrix.version }}-

      - name: Build
        run: |
          docker buildx build \
            --tag kooldev/php:${{ matrix.version }}
            --cache-from type=local,src=/tmp/.buildx-cache
            --cache-to type=local,dest=/tmp/.buildx-cache
            --file ${{ matrix.version }}/Dockerfile

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push to DockerHub