name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 7.1, 7.2, 7.3, 7.4 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build images
      run: |
        docker build --pull -t kooldev/php:${{ matrix.version }} ${{ matrix.version }}
        docker build --pull -t kooldev/php:${{ matrix.version }}-prod ${{ matrix.version }}-prod
        docker build -t kooldev/php:${{ matrix.version }}-wkhtmltopdf ${{ matrix.version }}-wkhtmltopdf
        docker build -t kooldev/php:${{ matrix.version }}-wkhtmltopdf-prod ${{ matrix.version }}-wkhtmltopdf-prod

    - name: Build images nginx
      if: matrix.version == '7.4'
      run: |
        docker build -t kooldev/php:${{ matrix.version }}-nginx ${{ matrix.version }}-nginx
        docker build -t kooldev/php:${{ matrix.version }}-nginx-prod ${{ matrix.version }}-nginx-prod
        docker build -t kooldev/php:${{ matrix.version }}-nginx-wkhtmltopdf ${{ matrix.version }}-nginx-wkhtmltopdf
        docker build -t kooldev/php:${{ matrix.version }}-nginx-wkhtmltopdf-prod ${{ matrix.version }}-nginx-wkhtmltopdf-prod

        docker build -t kooldev/php:${{ matrix.version }}-full ${{ matrix.version }}-full
        docker build -t kooldev/php:${{ matrix.version }}-full-prod ${{ matrix.version }}-full-prod
        docker build -t kooldev/php:${{ matrix.version }}-full-wkhtmltopdf ${{ matrix.version }}-full-wkhtmltopdf
        docker build -t kooldev/php:${{ matrix.version }}-full-wkhtmltopdf-prod ${{ matrix.version }}-full-wkhtmltopdf-prod

    - name: Test docker images
      run: |
        for suffix in '' -prod -wkhtmltopdf -wkhtmltopdf-prod; do
          docker run kooldev/php:${{ matrix.version }}$suffix php -v
          docker run kooldev/php:${{ matrix.version }}$suffix composer -V
          docker run -e ASUSER=1000 kooldev/php:${{ matrix.version }}$suffix php -v
          docker run -e ASUSER=1000 kooldev/php:${{ matrix.version }}$suffix composer -V
          docker run kooldev/php:${{ matrix.version }}$suffix php -m
          docker run -e ENABLE_XDEBUG=true kooldev/php:${{ matrix.version }}$suffix php -m
        done

    - name: Test docker images nginx
      if: matrix.version == '7.4'
      run: |
        for suffix in -nginx -nginx-prod -nginx-wkhtmltopdf -nginx-wkhtmltopdf-prod -full -full-prod -full-wkhtmltopdf -full-wkhtmltopdf-prod; do
          docker run kooldev/php:${{ matrix.version }}$suffix php -v
          docker run kooldev/php:${{ matrix.version }}$suffix composer -V
          docker run -e ASUSER=1000 kooldev/php:${{ matrix.version }}$suffix php -v
          docker run -e ASUSER=1000 kooldev/php:${{ matrix.version }}$suffix composer -V
          docker run kooldev/php:${{ matrix.version }}$suffix php -m
          docker run -e ENABLE_XDEBUG=true kooldev/php:${{ matrix.version }}$suffix php -m
          docker run kooldev/php:${{ matrix.version }}$suffix nginx -v
          docker run kooldev/php:${{ matrix.version }}$suffix supervisord version
        done

    - name: Push to Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push kooldev/php:${{ matrix.version }}
        docker push kooldev/php:${{ matrix.version }}-prod
        docker push kooldev/php:${{ matrix.version }}-wkhtmltopdf
        docker push kooldev/php:${{ matrix.version }}-wkhtmltopdf-prod

    - name: Push to Hub nginx
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.version == '7.4'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push kooldev/php:${{ matrix.version }}-nginx
        docker push kooldev/php:${{ matrix.version }}-nginx-prod
        docker push kooldev/php:${{ matrix.version }}-nginx-wkhtmltopdf
        docker push kooldev/php:${{ matrix.version }}-nginx-wkhtmltopdf-prod

        docker push kooldev/php:${{ matrix.version }}-full
        docker push kooldev/php:${{ matrix.version }}-full-prod
        docker push kooldev/php:${{ matrix.version }}-full-wkhtmltopdf
        docker push kooldev/php:${{ matrix.version }}-full-wkhtmltopdf-prod
